/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package employeedataapp.ui;

import employeedataapp.model.Employee;
import employeedataapp.model.EmployeeData;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sayali Dalvi
 */
public class ViewEmployeePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmployeePanel
     */
    
    public EmployeeData employeeData;
    public static final String COLUMNS[] = {"ID", "NAME", "GENDER", "LEVEL", "TEAM",};
    private DefaultTableModel tableModel;
    
    
    public ViewEmployeePanel() {
        initComponents();
    }

    public ViewEmployeePanel(EmployeeData employeeData) {
        initComponents();
        this.employeeData = employeeData;
        initialiseTable(this.employeeData);
        
    }
    
    public void initialiseTable(EmployeeData employeeData){
        String[][] data = new String[employeeData.getEmployeeList().size()][5];
        int i=0;
        for( Employee employee : employeeData.getEmployeeList()){
            data[i][0] = String.valueOf(employee.getEmployeeId());
            data[i][1] = employee.getName();
            data[i][2] = employee.getGender();
            data[i][3] = employee.getLevel();
            data[i][4] = employee.getTeamInfo();
//            System.out.println("Row Data : "+data[i][0]+data[i][1]+data[i][2]+data[i][3]+data[i][4]);
            i++;
        }
 
        // Initializing the JTable
        tableModel = new DefaultTableModel(data, COLUMNS);
        jTable1.setModel(tableModel);
        
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        @Override
        public void valueChanged(ListSelectionEvent event) {
            // do some actions here, for example
            // print first column value from selected row
            System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        }
        });
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
